### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by Buddybenj** [LuigiBlood/64dddump#1]
I can't find a license on this software. There are many problems with not having a license: most importantly, it is automatically "All Rights Reserved" with no license, so it is therefore not free and open-source.

http://choosealicense.com/

If you wish to put the software in the public domain, you can use CC0 to do that.

**Comment by LuigiBlood** [comment]
Actually... most of the code is like stolen from Nintendo SDK demos. That's why I didn't license.

EDIT: I did put the code for posterity but if it needs to be removed... I'll do that ASAP.
